services:
  smtp_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SMTP_SERVER_PORT}:${SMTP_SERVER_PORT}"
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    volumes:
      - ./attachments:/smtp-server/attachments
      - "./${DB_NAME}:/smtp-server/${DB_NAME}"
  client_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_APP_PORT}:${CLIENT_APP_PORT}"