services:
  smtp_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SMTP_SERVER_PORT}:${SMTP_SERVER_PORT}"
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    volumes:
      - ./attachments:/smtp-server/attachments
      - "./${DB_NAME}:/smtp-server/${DB_NAME}"
  client_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_APP_PORT}:${PROXY_SERVER_PORT}"
  web_server:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${PROXY_SERVER_PORT}:${PROXY_SERVER_PORT}"
    volumes:
     - ./client/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client_app 
